#!/usr/bin/env bash

export CARGO_NET_GIT_FETCH_WITH_CLI=true
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export CARGO_HTTP_CAINFO=/var/cache/ca-certs/anchors/ca-certificates.crt
export CC=clang
export CXX=clang++
export CC_x86_64_unknown_linux_gnu=clang
export CXX_x86_64_unknown_linux_gnu=clang++
export AR=/usr/bin/llvm-ar
export RANLIB=/usr/bin/llvm-ranlib
export NM=/usr/bin/llvm-nm
export AR_x86_64_unknown_linux_gnu=/usr/bin/llvm-ar
export RANLIB_x86_64_unknown_linux_gnu=/usr/bin/llvm-ranlib
export NM_x86_64_unknown_linux_gnu=/usr/bin/llvm-nm
export CRATE_CC_NO_DEFAULTS=1
export CARGO_BUILD_JOBS=16
export PCRE2_SYS_STATIC=1
export OPENSSL_STATIC=yes
export OPENSSL_LIB_DIR=/usr/lib64/
export OPENSSL_INCLUDE_DIR=/usr/include/
export LLVM_PROFILE_FILE="/var/tmp/pgo/code-%p-%m.profraw"
##
export PGO_GEN="-fprofile-generate=/var/tmp/pgo/"
export CFLAGS_GENERATE="-flto=full -fuse-ld=lld -fPIC $PGO_GEN"
#
export PGO_GEN_RUST="-Cprofile-generate=/var/tmp/pgo/"
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS_GENERATE="-Cembed-bitcode=yes -Clink-dead-code=yes -Clto=fat -Copt-level=3 -Clinker-plugin-lto=on -Ccodegen-units=1 -Cpanic=abort -Clinker=/usr/bin/clang -Clink-arg=-fuse-ld=lld $PGO_GEN_RUST"
export RUSTFLAGS_GENERATE="-Cembed-bitcode=yes -Clink-dead-code=yes -Clto=fat -Copt-level=3 -Clinker-plugin-lto=on -Ccodegen-units=1 -Cpanic=abort -Clinker=/usr/bin/clang -Clink-arg=-fuse-ld=lld $PGO_GEN_RUST"
export CARGO_HOST_RUSTFLAGS_GENERATE="-Cembed-bitcode=yes -Clink-dead-code=yes -Copt-level=3 -Clinker-plugin-lto=on -Ccodegen-units=1 -Cpanic=abort -Clinker=/usr/bin/clang -Clink-arg=-fuse-ld=lld $PGO_GEN_RUST"
##
export PGO_USE="-fprofile-use=/var/tmp/pgo/rustprofile.profdata"
export CFLAGS_USE="-flto=full -fuse-ld=lld -fPIC $PGO_USE"
#
export PGO_USE_RUST="-Cprofile-use=/var/tmp/pgo/rustprofile.profdata"
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS_USE="-Cembed-bitcode=yes -Clink-dead-code=yes -Clto=fat -Copt-level=3 -Clinker-plugin-lto=on -Ccodegen-units=1 -Cpanic=abort -Clinker=/usr/bin/clang -Clink-arg=-fuse-ld=lld $PGO_USE_RUST"
export RUSTFLAGS_USE="-Cembed-bitcode=yes -Clink-dead-code=yes -Clto=fat -Copt-level=3 -Clinker-plugin-lto=on -Ccodegen-units=1 -Cpanic=abort -Clinker=/usr/bin/clang -Clink-arg=-fuse-ld=lld $PGO_USE_RUST"
export CARGO_HOST_RUSTFLAGS_USE="-Cembed-bitcode=yes -Clink-dead-code=yes -Copt-level=3 -Clinker-plugin-lto=on -Ccodegen-units=1 -Cpanic=abort -Clinker=/usr/bin/clang -Clink-arg=-fuse-ld=lld $PGO_USE_RUST"

clean() {
  cargo clean || :
  rm out/bin/rsmain || :
  rm ./rsmain || :
  rm ./*.rmeta || :
  rm ./*.o || :
  rm -rf false/ || :
  rm ./libinteresting.rlib || :
  rm ./libxyz.a || :
  rm ./clib.o || :
  rm /var/tmp/pgo/rustprofile.profdata || :
  rm /var/tmp/pgo/*.profraw || :
}

first() {
  export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS="${CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS_GENERATE}"
  export RUSTFLAGS="${RUSTFLAGS_GENERATE}"
  export CARGO_HOST_RUSTFLAGS="${CARGO_HOST_RUSTFLAGS_GENERATE}"
  export CFLAGS="${CFLAGS_GENERATE}"
  cargo clean || :
  rm out/bin/rsmain || :
  rm ./rsmain || :
  rm ./*.rmeta || :
  rm ./*.o || :
  rm -rf false/ || :
  rm ./libinteresting.rlib || :
  rm libxyz.a || :
  rm clib.o || :
  rm /var/tmp/pgo/rustprofile.profdata || :
  rm /var/tmp/pgo/*.profraw || :
  /usr/bin/clang ./clib.c $CFLAGS -c -o ./clib.o
  /usr/bin/llvm-ar crus ./libxyz.a ./clib.o
  mkdir -p target/x86_64-unknown-linux-gnu/release/deps/
  cp -f ./libxyz.a target/x86_64-unknown-linux-gnu/release/deps/
  cargo install -Zunstable-options -Zhost-config -Ztarget-applies-to-host --jobs 16 -vv --offline --locked --no-track --force --profile release --target x86_64-unknown-linux-gnu --path . --root out/
#   cargo rustc -Zunstable-options -Zhost-config -Ztarget-applies-to-host --jobs 16 -vv --offline --locked --profile release --target x86_64-unknown-linux-gnu -- --emit llvm-bc
#     rustc --verbose $RUSTFLAGS_GENERATE -L. ./interesting.rs
# #     rustc --verbose $RUSTFLAGS_GENERATE -L. --emit=llvm-ir -o ./rsmain1.ll ./main.rs
#     rustc --verbose $RUSTFLAGS_GENERATE -L. -o ./rsmain ./main.rs
  out/bin/rsmain
  exa --long --all --icons out/bin/rsmain
  ldd out/bin/rsmain
}

second() {
  export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS="${CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS_USE}"
  export RUSTFLAGS="${RUSTFLAGS_USE}"
  export CARGO_HOST_RUSTFLAGS="${CARGO_HOST_RUSTFLAGS_USE}"
  export CFLAGS="${CFLAGS_USE}"
  cargo clean || :
  rm out/bin/rsmain || :
  rm ./rsmain || :
  rm ./*.rmeta || :
  rm ./*.o || :
  rm -rf false/ || :
  rm ./libinteresting.rlib || :
  rm libxyz.a || :
  rm clib.o || :
  /usr/bin/llvm-profdata merge -o /var/tmp/pgo/rustprofile.profdata /var/tmp/pgo/*.profraw || :
  /usr/bin/clang ./clib.c $CFLAGS -c -o ./clib.o
  /usr/bin/llvm-ar crus ./libxyz.a ./clib.o
  mkdir -p target/x86_64-unknown-linux-gnu/release/deps/
  cp -f ./libxyz.a target/x86_64-unknown-linux-gnu/release/deps/
  cargo install -Zunstable-options -Zhost-config -Ztarget-applies-to-host --jobs 16 -vv --offline --locked --no-track --force --profile release --target x86_64-unknown-linux-gnu --path . --root out/
#   rustc --verbose $RUSTFLAGS_USE -L. ./interesting.rs
# #     rustc --verbose $RUSTFLAGS_USE -L. --emit=llvm-ir -o ./rsmain2.ll ./main.rs
#   rustc --verbose $RUSTFLAGS_USE -L. -o ./rsmain ./main.rs
  out/bin/rsmain
  exa --long --all --icons out/bin/rsmain
  ldd out/bin/rsmain
#   cargo rustc -Zunstable-options -Zhost-config -Ztarget-applies-to-host --jobs 16 -vv --offline --locked --profile release --target x86_64-unknown-linux-gnu  -- --emit llvm-bc
}

case $1 in
  c)
    clean;
    ;;
  1)
    first;
    ;;
  2)
    second;
    ;;
  *)
    echo "Unknown option"
    ;;
esac
